apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 8443
      protocol: TCP
  selector:
    app: greeter-server
